version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_PB_URL_LOCAL: ${NEXT_PUBLIC_PB_URL_LOCAL}
      - NEXT_PUBLIC_PB_URL_REMOTE: ${NEXT_PUBLIC_PB_URL_REMOTE}
      - NEXT_PUBLIC_PB_USER_COLLECTION: ${NEXT_PUBLIC_PB_USER_COLLECTION}
      - NEXT_PUBLIC_PB_IG_ACCOUNTS_COLLECTION: ${NEXT_PUBLIC_PB_IG_ACCOUNTS_COLLECTION}
      - NEXT_PUBLIC_PB_SCHEDULED_IG_REELS_COLLECTION: ${NEXT_PUBLIC_PB_SCHEDULED_IG_REELS_COLLECTION}
    args:
      - NEXT_PUBLIC_PB_URL_LOCAL: ${NEXT_PUBLIC_PB_URL_LOCAL}
      - NEXT_PUBLIC_PB_URL_REMOTE: ${NEXT_PUBLIC_PB_URL_REMOTE}
      - NEXT_PUBLIC_PB_USER_COLLECTION: ${NEXT_PUBLIC_PB_USER_COLLECTION}
      - NEXT_PUBLIC_PB_IG_ACCOUNTS_COLLECTION: ${NEXT_PUBLIC_PB_IG_ACCOUNTS_COLLECTION}
      - NEXT_PUBLIC_PB_SCHEDULED_IG_REELS_COLLECTION: ${NEXT_PUBLIC_PB_SCHEDULED_IG_REELS_COLLECTION}

