name: CD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: shut down the image
        run: docker-compose down
      - name: remove dangling images
        run: docker image prune --all --force
      - name: rebuild the image
        run: docker-compose build --no-cache
      - name: run the image
        run: docker-compose up -d

    env:
      NEXT_PUBLIC_PB_URL_LOCAL: ${{ vars.NEXT_PUBLIC_PB_URL_LOCAL }}
      NEXT_PUBLIC_PB_URL_REMOTE: ${{ vars.NEXT_PUBLIC_PB_URL_REMOTE }}
      NEXT_PUBLIC_PB_USER_COLLECTION: ${{ vars.NEXT_PUBLIC_PB_USER_COLLECTION }}
      NEXT_PUBLIC_PB_IG_ACCOUNTS_COLLECTION: ${{ vars.NEXT_PUBLIC_PB_IG_ACCOUNTS_COLLECTION }}
      NEXT_PUBLIC_PB_SCHEDULED_IG_REELS_COLLECTION: ${{ vars.NEXT_PUBLIC_PB_SCHEDULED_IG_REELS_COLLECTION }}
